### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by darleybarreto** [neuronika/neuronika#59]
Hi folks,

First of all I would like to say what impressive work so far! I am a person with engineering and research background (ML/DL). I have been using PyTorch and TensorFlow for a while now, and I must say that the architecture is similar and feels like a smooth transition from PyTorch to neuronika, which is amazing. 

I am a bit familiar with the Julia ecosystem too, specially Flux, Zygote and JuliaGPU. This ecosystem has a few points that might be interesting to discuss:

1. Abstraction over the autodiff machinery
2. Abstraction over devices
3. (Future abstraction over operations/devices using KernelAbstractions)

What you folks think about having a small abstraction over the choice of the autodiff (separating from the framework itself)? How would Rust play along with GPUs (Nvidia, AMD)? For instance, JuliaGPU has a compiler and a GC to deal with allocation of memory in the device. Would it be easy to compile Rust-y kernels directly to the GPU?

Best wishes,

**Comment by frjnn** [comment]
Thanks.

I'm not familiar with Julia at all, but I'm always willing to expand my horizons, would you be do kind to provide me some articles to begin with?

Concerning gp-GPUS, frankly, I don't really know, neuronika is built on top of ndarray and we'll probably wait and see what happens.

**Comment by darleybarreto** [comment]
> I'm not familiar with Julia at all, but I'm always willing to expand my horizons, would you be so kind to provide me some articles to begin with?

#### GPUs
I don't know how "old" [this](https://www.youtube.com/watch?v=7Yq1UyncDNc) video is, but I would recommend giving a look. Also the official [tutorial](https://cuda.juliagpu.org/stable/tutorials/introduction/) definitely helps. 

#### Flux
[Deep Learning with Flux - A 60 Minute Blitz](https://fluxml.ai/tutorials/2020/09/15/deep-learning-flux.html). Afaik, Zygote is a bit less explored in tutorials, but there is a [paper](https://arxiv.org/abs/1810.07951). Either way, it's a possible autodiff for Flux, there's also an "old" one called [ForwardDiff](https://github.com/JuliaDiff/ForwardDiff.jl) and a "newer", which is not ready yet.
