### ISSUE TITLE
Enhancement of reduction procedure

### ISSUE THREAD

**Issue by ste-pac** [neuronika/neuronika#63]
## Description of the problem
Let's talk for a moment about the *reduction mechanics* implemented in `neuronika`. Currently, during a backward pass, we "shrink" the gradient entering each node by calling the two functions `reduce` and `sum_axis_inplace`.

<details><summary>Functions Code</summary>

```rust
fn sum_axis_inplace(arr: &mut DynTensor, axis: Axis) {
    let (first, rest) = arr.view_mut().split_at(axis, 1);
    Zip::from(first.remove_axis(axis))
        .and(rest.lanes(axis))
        .for_each(|dst, src| *dst += src.sum());
    arr.index_axis_inplace(axis, 0);
}

pub fn reduce<D: Dimension, E: Dimension>(dest: &Tensor<D>, src: &Tensor<E>) -> DynTensor {
    let mut dyn_rhs = src.clone().into_dyn(); // <- Very costly operation!

    unsafe {
        while (*(&dyn_rhs as *const DynTensor)).ndim() > dest.ndim() {
            sum_axis_inplace(&mut dyn_rhs, Axis(0));
        }
    }

    for (axis, size) in dest.shape().iter().enumerate() {
        if *size == 1 {
            sum_axis_inplace(&mut dyn_rhs, ndarray::Axis(axis));
            dyn_rhs.insert_axis_inplace(ndarray::Axis(axis));
        }
    }

    dyn_rhs
}
```
</details>

As you can see in the first line of `reduce`, every time it is executed it does a `.clone()`, but since the type on which it's executed is an `Array` that uniquely owns its content, we are actually allocating and copying it. Also, in a scenario where `src` and `dest` shapes are equal, this operation is completely useless as we can simply add them together.

## Possible solution
One way to avoid all of these penalties is to introduce a new `Reducer` structure that contains a buffer with the same capacity as the largest gradient on which the reduction has to be performed. If and when this operation has to be performed, the contents of the input tensor are copied into the buffer, which is then used to generate a new `ArrayViewMut` on which the actual accumulation will take place.

<details>
<summary>Solution Code</summary>

```rust
pub struct Reducer {
    buffer: Vec<f32>,
}

impl Reducer {
    fn sum_axis_inplace(arr: &mut ArrayViewMut<f32, IxDyn>, axis: Axis) {
        let (first, rest) = arr.view_mut().split_at(axis, 1);
        Zip::from(first.remove_axis(axis))
            .and(rest.lanes(axis))
            .for_each(|dst, src| *dst += src.sum());
        arr.index_axis_inplace(axis, 0);
    }

    fn load(&mut self, src: &ArrayView<f32, IxDyn>) {
        let src_len = src.len();

        assert!(src_len <= self.buffer.capacity());

        unsafe {
            ptr::copy_nonoverlapping(src.as_ptr(), self.buffer.as_mut_ptr(), src_len);
            self.buffer.set_len(src_len);
        }
    }

    pub fn new(cap: usize) -> Self {
        assert_ne!(cap, 0);

        Self {
            buffer: Vec::with_capacity(cap),
        }
    }

    pub fn reduce<D: Dimension>(&mut self, dst: &mut Array<f32, D>, src: ArrayView<f32, IxDyn>) {
        let excess = src.ndim() - dst.ndim();
        let to_shrink = src.shape()[excess..src.ndim()]
            .iter()
            .enumerate()
            .filter(|(_, len)| **len == 1)
            .map(|(id, _)| id)
            .collect::<Vec<_>>();

        if excess == 0 && to_shrink.is_empty() {
            // dst.assign(&src);
            return;
        }

        self.load(&src);
        let mut src =
            unsafe { ArrayViewMut::from_shape_ptr(src.raw_dim(), self.buffer.as_mut_ptr()) };

        for _ in 0..excess {
            Reducer::sum_axis_inplace(&mut src, Axis(0));
        }

        for axis in to_shrink {
            Reducer::sum_axis_inplace(&mut src, Axis(axis));
            src.insert_axis_inplace(Axis(axis));
        }

        // dst.assign(&src);
    }
}
```
</details>

## Test Configuration
Both these versions have been tested on the following code with the `--release` flag twice, one with `valgrind` to assess the memory usage, and one without for the completion time. 

<details>
<summary>New Code Test</summary> 

```rust
const TRIES: usize = 16;

let mut reducer = Reducer::new(1_024 * 1_024 * 4);
let src = Array::from_elem((1_024, 1_024, 4), 1.);
let mut dst = Array::from_elem((1_024, 4), 0.);
let res = (0..TRIES)
    .map(|_| {
        let start = Instant::now();
        for _ in 0..1_024 {
            reducer.reduce(&mut dst, src.view().into_dyn());
        }
        start.elapsed().as_millis()
    })
    .sum::<u128>();
println!(
    "Mean elapsed time: {} milliseconds",
    res as f64 / TRIES as f64
);
```
</details>

<details><summary>Old Code Test</summary>

```rust
const TRIES: usize = 16;

let src = Array::from_elem((1_024, 1_024, 4), 1.);
let dst = Array::from_elem((1_024, 4), 0.);
let res = (0..TRIES)
    .map(|_| {
        let start = Instant::now();
        for _ in 0..1_024 {
            neuronika::variable::node::reduce(&dst, &src);
        }
        start.elapsed().as_millis()
    })
    .sum::<u128>();
println!(
    "Mean elapsed time: {} milliseconds",
    res as f64 / TRIES as f64
);
```
</details>

## Results 
<table style="border-collapse:collapse;border-spacing:0;border:none" class="tg"><thead><tr><th style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:bold;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">Version</th><th style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:bold;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">Iterations</th><th style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:bold;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">Source</th><th style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:bold;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">Destination</th><th style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:bold;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">Time (ms)</th><th style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:bold;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">Allocations</th><th style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:bold;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">Bytes Used</th></tr></thead><tbody><tr><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-style:italic;overflow:hidden;padding:10px 5px;text-align:center;text-decoration:underline;vertical-align:middle;word-break:normal">Current</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal" rowspan="2">1'024</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal" rowspan="2">(1'024, 1'024, 4)</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal" rowspan="2">(1'024, 4)</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">10'931.81</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">1,037</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">17,196,664,945</td></tr><tr><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-style:italic;overflow:hidden;padding:10px 5px;text-align:center;text-decoration:underline;vertical-align:middle;word-break:normal">Proposed</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">9'561.56</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">14</td><td style="border-color:inherit;border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:center;vertical-align:middle;word-break:normal">33,572,977</td></tr></tbody></table>

Looking at the numbers, we can see that this new version, even on only `1'024` iterations, is almost `1.5` seconds faster, and uses `512` times less memory.

**Comment by frjnn** [comment]
Interesting! I have a couple of questions: when does `Reducer` gets freed? And who owns it?

**Comment by frjnn** [comment]
This procedure works in-place and does not allocate. I briefly tested it and it seems to work. I would extensively test it before adopting it anyways.

```rust
fn accumulate<D, E>(target: &mut Array<f32, D>, source: &Array<f32, E>)
where
    D: Dimension,
    E: Dimension,
{
    // context: source is a tensor whose shape is the result of broadcasting between target
    // and some other.
    let target_dim = target.raw_dim();

    // base case: when target is the broader
    if let Some(smaller) = source.broadcast(target.raw_dim()) {
        *target += &smaller;
    } else {
        let source_dim = source.raw_dim();

        let target_dims = target_dim.ndim();
        // computes the difference between the number of dimensions
        let k = source_dim.ndim() - target_dims;
        let axis_zero_size = source_dim.slice().iter().take(k).product::<usize>();

        let mut reshape = D::Larger::zeros(target_dims + 1);
        reshape[0] = axis_zero_size;

        for (r, s) in std::iter::zip(
            reshape.slice_mut().iter_mut().skip(1),
            source_dim.slice().iter().skip(k),
        ) {
            *r = *s;
        }
        // reshapes such that the sub-views match the dimensionality of target
        let views = source.view().into_shape(reshape).unwrap();

        for view in views.axis_iter(Axis(0)) {
            let view_dim = view.raw_dim();
            // accumulates using the outermost axis
            for (i, (t_dim, v_dim)) in
                std::iter::zip(target_dim.slice(), view_dim.slice()).enumerate()
            {
                // dimensions can either be equal or 1
                if t_dim != v_dim {
                    let axis = ndarray::Axis(i);
                    let mut lanes_v = view.lanes(axis).into_iter();

                    while lanes_v.len() > 0 {
                        let mut lanes_t = target.lanes_mut(axis).into_iter();
                        while let Some(mut lane_t) = lanes_t.next() {
                            if let Some(lane_v) = lanes_v.next() {
                                if lane_t.len() == 1 {
                                    lane_t[0] += lane_v.sum();
                                } else {
                                    lane_t += &lane_v;
                                }
                            }
                        }
                    }
                    break;
                }
            }
        }
    }
}
```

**Comment by ste-pac** [comment]
We ran some tests on different machines and we can conclude that the in-place variant is `1.3 ~ 4.6` times more efficient than the buffered one, so we will implement [this] version in the library.

Well done @frjnn!

[that]: https://github.com/neuronika/neuronika/issues/63#issuecomment-1090076882
