### ISSUE TITLE
LOC per file is too big to be maintainable

### ISSUE THREAD

**Issue by russellwmy** [neuronika/neuronika#64]
To enable more  developer can be contributed, it is better to have small files instead of 5k LOC

**Comment by frjnn** [comment]
We are aware of this, we will fix this in the upcoming version.

**Comment by russellwmy** [comment]
You can break down the framework into different packages as well.

for example
- neuronika_core
- neuronika_ io
- neuronika_xxz

**Comment by frjnn** [comment]
By moving the tests in separate files we are able to obtain a reasonable number of loc per file.
