### ISSUE TITLE
An error occur when i run the example

### ISSUE THREAD

**Issue by xuexl** [neuronika/neuronika#97]
Hi,  I am a beginner of rust, when i run the example code of "quickstart" that is in the directory of examples, an error occur, the error information is :

> error[E0277]: the trait bound `NeuralNetwork: serde::de::Deserialize<'_>` is not satisfied
    --> src/main.rs:51:21
     |
51   |     let json_data = serde_json::from_str(
     |                     ^^^^^^^^^^^^^^^^^^^^ the trait `serde::de::Deserialize<'_>` is not implemented for `NeuralNetwork`
     |
note: required by a bound in `serde_json::from_str`
    --> /home/lin/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.79/src/de.rs:2611:8
     |
2611 |     T: de::Deserialize<'a>,
     |        ^^^^^^^^^^^^^^^^^^^ required by this bound in `serde_json::from_str`

I know the mean, but need i to write the code of "Deserialize trait" or , maybe, the reason is the error config of my toml file.

The content of my toml file is :

> 
[dependencies]
neuronika = { git = "https://github.com/neuronika/neuronika" }
csv = "1.1.6"
itertools = "0.10.3"
ndarray = {version = "0.15.4", features = ["rayon"]}
ndarray-rand = "0.14.0"
rand = "0.8.4"
rand_distr = "0.4.2"
rayon = "1.5.1"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"

[features]
blas = ["ndarray/blas"]
matrixmultiply-threading = ["ndarray/matrixmultiply-threading"]
serialize = ["ndarray/serde"]

Help me, please. Thank you .

**Comment by lodykas** [comment]
It probably is a error in your toml file; I can run it (latest commit as I wrote this)

I'm not an expert with cargo and toml, you can check the differences with the one on the root of this crate; but what strikes me is this part:
```
[[example]]
name = "quickstart"
required-features = ["serialize"]
```
As the command used to make it work was: `cargo run --example quickstart --features="serialize"`

**Comment by frjnn** [comment]
How are you trying to run the example? `cargo run --example quickstart --features="serialize"` should work.

**Comment by xuexl** [comment]
Thanks a lot .

I create a new project, and copy all the code of "qickstart.rs", then config the toml file. 
I think there must be some errors in my toml file.

And when i execute the command that "cargo run --example quickstart --features="serialize"",
It is ok, I get the successful result. 

The Neuronika project is so nice , I want to know it  more . 

Thanks again.

**Comment by lodykas** [comment]
Hello, 
after reading through [cargo's doc](https://doc.rust-lang.org/cargo/reference/features.html) (RTFM amirite?) I believe I found the solution if you want to avoid the flag for cargo:

```
[...]
[features]
default = ["serialize"] # this line allows you to enable it by default and avoid adding --feature
[...]
```


BTW: consider closing the issue as it isn't really a issue of neuronika itself. If you found a solution, also consider writing your conclusions to the associated discussion and mark it as 'solved'; this might help others with the same questions
